openapi: 3.0.3
info:
  title: SalesSparrow Accounts API's
  description: Following api's will be called from the SalesSparrow application
  version: '1.0'
servers:
  - url: https://sales.truesparrow.com/api
paths:
  /v1/accounts:
    get:
      description: Api will return the list of accounts 
      parameters:
        - name: q
          in: query
          description: Account Search String
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_ids:
                    type: array
                    items:
                      type: string
                      example:
                        - 'abc123abc'
                  account_map_by_id:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 'abc123abc'
                        name:
                          type: string
                          example: 'xyz'
