openapi: 3.0.3
info:
  title: SalesSparrow Users API's
  description: Following api's will be called from the sales sparrow application
  version: '1.0'
servers:
  - url: https://sales.truesparrow.com/api
paths:

  /v1/users/current:
    get:
      description: Api will return current user entity
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_user:
                    type: object
                    properties:
                      id: 
                        type: string
                        example: "0caa56f9-2abd-45b2-8469-e41d3e692eaa"
                      name:
                        type: string
                        example: 'sample user'
                      email:
                        type: string
                        example: 'sampleuser@gmail.com'