sequenceDiagram
  title Get Note Details
    participant ui as SalesSparrow App
    participant api as SalesSparrow API

    box Black 
    participant factory as SalesSparrow Factory 
    end
    participant server as SalesSparrow Server

    ui->>api:  Send request 
    note right of ui: Request: <br>GET {api_base_url}/api/v1/accounts/{account_id}/notes/{note_id}<br><br>query params:  <br>note_id (NoteId to fecth details of note)

    note over api: Validate and fetch user data from cookie
    alt If user not found
        api-->>ui: User Not Found
    end

    api->>factory: Send params

    opt Unsucessfull parameter handling
        api-->>ui: Invalid Parameters
    end

    factory->>server: Make salesforce composite api call
    note right of factory: Request: POST {instance_url}/services/data/v58.0/composite <br><br>Params: <br> requestType: GET<br> url: "/services/data/v58.0/query/?q=<br>SELECT Id, Title, TextPreview, ContentModifiedDate , CreatedBy.Name FROM ContentNote <br>WHERE Id = note_id<br>referenceId: "GetContentNotes"<br>

    factory->>server: Make salesforce api call for Content
    note right of factory: Request: POST {instance_url}/services/data/v58.0/sobjects/ContentNote/{{note_id}} 

    alt If any error from salesforce server
        server-->>factory: Error 
        factory-->>api: Error
        api-->>ui: Error Response 
    end

    server-->>factory: Salesforce Response
    note over factory:  Format Salesforce Response

    factory-->>api: Salessparrow Response
    note right of api: {note_details: {}}

    api-->>ui: Response
    note right of ui: Response body: <br> note_details<br><br>Response headers:<br> cookie 