sequenceDiagram
  title Delete Account Event
    participant ui as SalesSparrow Client
    participant api as SalesSparrow API
    participant exceptionHandler as Global Exception Handler
    participant validator as Param Validator(Interceptor)
    participant controller as AccountEventController
    participant service as DeleteAccountEvent Service
    participant factory as DeleteAccountEvent Factory
    participant crm as Salesforce DeleteAccountEvent Service
    participant CompositeRequestWrapper as CompositeRequest(Wrapper)
    participant salesforce as Salesforce

    ui->>api:  Send request 
    note right of ui: Request: <br>DELETE {api_base_url}/v1/accounts/{account_id}/events/{event_id}<br><br>path params:  <br>account_id [mandatory]<br>event_id [mandatory]


    note over api: Validate and fetch current user data from cookie<br>set currentUser attribute in request.<br><br>Refer this document for interceptor sequence diagram <br> './docs/sequenceDiagrams/Common/UserAuthIntercepter.mermaid'
    break If currentUser not found
        api-->>ui: Return 401 Error Response<br>currentUser Not Found
    end

    api->>validator: Validate path params

    break 
        alt If mandatory params not present in the body
            validator->>exceptionHandler: Throws exeption
            exceptionHandler-->>ui:Return 400 error response 
        else If account_id or event_id is not valid
            validator->>exceptionHandler: Throws exeption
            exceptionHandler-->>ui:Return 400 error response 
        end
    end

    validator->>controller: Send validated params<br>params: eventId, accountId
    
    controller->>service: Call deleteAccountEvent method of DeleteAccountEventService<br> params: request, eventId, accountId
    note over service: GetAttribute of currentUser from request<br>Which was set by interceptor

    service->>factory: Call deleteAccountEvent method of DeleteAccountEventFactory<br>params: currentUser, eventId
    note over factory: Based on currentUser identify CRM

    factory->>crm: Call deleteAccountEvent method of particular CRM service<br>params: currentUser, eventId

    note over crm: fetch salesforceUserId from request currentUser
    break If salesforceUserId is not present in currentUser.
        crm->>exceptionHandler: Throws exeption
        exceptionHandler-->>ui:Return 400 error response 
    end
    crm->>CompositeRequestWrapper: Send compositeBody to make request to salesforce<br>params: <br> List<requestType, url, referenceId>, salesforceUserId <br>

    CompositeRequestWrapper->>salesforce: Make salesforce composite api call with commmon helper function<br><br>Refer this document for commmon helper function sequence diagram <br> './docs/sequenceDiagrams/Common/OAuthRequestHelper.mermaid'
    note right of CompositeRequestWrapper: Request: POST {instance_url}/services/data/v58.0/composite <br><br>Params: <br> method: DELETE<br> url: "/services/data/v58.0/sobjects/ContentNote/${eventId}"<br>referenceId: "DeleteEvent"
    
    break 
        alt If 400 or 404 error from salesforce
        salesforce-->>CompositeRequestWrapper: Return 400 error response: INVALID_EVENT_ID
        CompositeRequestWrapper->>exceptionHandler: Throws exeption
        exceptionHandler-->>ui: Return 400 error response
        else
        salesforce-->>CompositeRequestWrapper:  Return 500 error response
        CompositeRequestWrapper->>exceptionHandler: Throws exeption
        exceptionHandler-->>ui: Return 500 error response
        end
    end

    salesforce-->>CompositeRequestWrapper: Response
    CompositeRequestWrapper-->>crm: Response

    crm-->>factory: Response
    factory-->>service: Response
    service-->> controller: Response
    controller-->>api: Response

    api-->>ui: Success:204
    note right of ui: Response body: <br> {}<br><br>Response headers:<br> cookie 