sequenceDiagram
    title Account Details

    participant CNS as CreateNoteScreen
    participant CTS as CreateTaskScreen
    participant ADS as AccountDetailScreen
    participant ADSVM as AccountDetailScreenViewModel
    participant NDS as NoteDetailScreen
    participant NDSVM as NoteDetailScreenViewModel
    participant TVM as ToastViewModel
    participant AS as ApiService
    participant S as Server


    ADS->>ADSVM: Request to fetch Account Details with Account ID
    ADSVM->>AS: Request to fetch Account Details
    AS-->>S: Send API Request
    note right of AS: GET {api_base_url}/v1/accounts/{accountId}
    ADSVM->>AS: Request to fetch Account Notes List
    AS-->>S: Send API Request
    note right of AS: GET {api_base_url}/v1/accounts/{accountId}/notes
    ADSVM->>AS: Request to fetch Account Tasks List
    AS-->>S: Send API Request
    note right of AS: GET {api_base_url}/v1/accounts/{accountId}/tasks
    

    break If any of the request fails
        S-->>AS: Error response
        AS->>ADSVM: response
        ADSVM->>TVM: error message
        TVM->>ADS: error message is displayed
    end
    
    S-->>AS: Success response
    AS->>ADSVM: response
    ADSVM->>ADS: Propagates response
    note over ADS: Displays account details, notes list and tasks list

    alt if user clicks on any notes 
        ADS ->> NDS: navigate to note detail screen with Note Id and Account Id
        NDS ->> NDSVM: Request to Fetch Note Detail with Note Id
        NDSVM ->> AS: Send API Request
        note right of AS: GET {api_base_url}/v1/accounts/{accountId}/notes/{noteId}

        break If any of the request fails
            S-->>AS: Error response
            AS->>NDSVM: response
            NDSVM->>NDS: error message
            note over NDS: display error message

        end

        S-->>AS: Success response
        AS->>NDSVM: response
        NDSVM->>NDS: Propagates response
        note over NDS: Displays note details

    end

    alt if user clicks on add note button
        ADS ->> CNS: navigate to create note screen
    else if user clicks on add task button
        ADS ->> CTS: navigate to create task screen
    end