sequenceDiagram
    title Edit Task

    participant TDS as TaskDetailScreen/<br>EditTaskScreen
    participant TVM as ToastViewModel
    participant TDSVM as TaskDetailScreenViewModel
    participant AS as ApiService
    participant S as Server

    TDS->>TDSVM: Request to edit task with accountId, taskId and task details
    TDSVM->>AS: Invoke editTask method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/tasks/{taskId}

    break If the request fails
        S-->>AS: Error response
        AS->>TDSVM: response
        TDSVM->>TVM: error message
        TVM->>TDS: error message is displayed
    end

    S-->>AS: Success response
    AS->>TDSVM: Response
    TDSVM->>TDS: Response message
    note over TDS: Task is Updated