sequenceDiagram
    title Edit Task

    participant ETS as EditTaskScreen
    participant TVM as ToastViewModel
    participant ETVM as EditTaskScreenViewModel
    participant AS as ApiService
    participant S as Server

    ETS->>ETVM: Request to edit task with accountId, taskId and task details
    ETVM->>AS: Invoke editTask method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/tasks/{taskId}

    break If the request fails
        S-->>AS: Error response
        AS->>ETVM: response
        ETVM->>TVM: error message
        TVM->>ETS: error message is displayed
    end

    S-->>AS: Success response
    AS->>ETVM: Response
    ETVM->>ETS: Response message
    note over ETS: Task is Updated