sequenceDiagram
    title Edit Event

    participant ADS as AccountDetailScreen
    participant TVM as ToastViewModel
    participant ADSVM as AccountDetailScreenViewModel
    participant AS as ApiService
    participant S as Server

    ADS->>ADSVM: Request to edit note with accountId, eventId and event details
    ADSVM->>AS: Invoke editEvent method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/events/{eventId}

    break If the request fails
        S-->>AS: Error response
        AS->>ADSVM: response
        ADSVM->>TVM: error message
        TVM->>ADS: error message is displayed
    end

    S-->>AS: Success response
    AS->>ADSVM: Response
    ADSVM->>ADS: Response message
    note over ADS: Event is Updated