sequenceDiagram
    title Edit Note

    participant ENS as EditNoteScreen
    participant TVM as ToastViewModel
    participant ENVM as EditNoteScreenViewModel
    participant AS as ApiService
    participant S as Server

    ENS->>ENVM: Request to edit note with accountId, noteId and note details
    ENVM->>AS: Invoke editNote method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/notes/{noteId}

    break If the request fails
        S-->>AS: Error response
        AS->>ENVM: response
        ENVM->>TVM: error message
        TVM->>ENS: error message is displayed
    end

    S-->>AS: Success response
    AS->>ENVM: Response
    ENVM->>ENS: Response message
    note over ENS: Note is Updated