sequenceDiagram
    title Edit Note

    participant NDS as NoteDetailScreen/<br>EditNoteScreen
    participant TVM as ToastViewModel
    participant NDSVM as NoteDetailScreenViewModel
    participant AS as ApiService
    participant S as Server

    NDS->>NDSVM: Request to edit note with accountId, noteId and note details
    NDSVM->>AS: Invoke editNote method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/notes/{noteId}

    break If the request fails
        S-->>AS: Error response
        AS->>NDSVM: response
        NDSVM->>TVM: error message
        TVM->>NDS: error message is displayed
    end

    S-->>AS: Success response
    AS->>NDSVM: Response
    NDSVM->>NDS: Response message
    note over NDS: Note is Updated