sequenceDiagram
    title Edit Event

    participant EDS as EditDetailScreen/<br>EditEventScreen
    participant TVM as ToastViewModel
    participant EDSVM as EventDetailScreenViewModel
    participant AS as ApiService
    participant S as Server

    EDS->>EDSVM: Request to edit event with accountId, eventId and event details
    EDSVM->>AS: Invoke editEvent method
    AS-->>S: Send API Request
    note right of AS: PUT {api_base_url}/v1/accounts/{accountId}/events/{eventId}

    break If the request fails
        S-->>AS: Error response
        AS->>EDSVM: response
        EDSVM->>TVM: error message
        TVM->>EDS: error message is displayed
    end

    S-->>AS: Success response
    AS->>EDSVM: Response
    EDSVM->>EDS: Response message
    note over EDS: Event is Updated