sequenceDiagram
    title Create Note

    participant HS as HomeScreen
    participant NS as NoteScreen
    participant SAS as SearchAccountScreen
    participant CT as CustomToast
    participant NVM as NotesViewModel
    participant NR as NotesRepository
    participant S as Server

    alt Create Note from Home Screen
        HS->>NS: Naviagte to note screen

       alt  Account is not selected
            NS->>SAS: Search account flow
            SAS-->>NS: Return selected account
        end

        NS->>NVM : clicks on Save note
        NVM->>NR: Invoke Save note method with account_id and note_text
        NR->>S : Request: Save note
        note right of NR: POST {api_base_url}/{account_id}/notes

    break If request fails
        S-->>NR: Error response
        NR->>NVM: response
        NVM->>CT: Displays error toast message
    end
    
    S-->>NR: Success response
    NR->>NVM: response
    NVM->>CT: Displays success toast message
    NVM->>NS: Displays created note

    end

