sequenceDiagram
    title Salesforce Login Flow

    participant U as User
    participant SSA as SalesSparrowApp
    participant AM as AndroidManifest
    participant LS as LoginScreen
    participant HS as HomeScreen
    participant AVM as AuthenticationViewModal
    participant AR as AuthenticationRepository
    participant S as Server
    participant B as Browser
    participant SF as Salesforce

    U->>SSA: Initiates App launch
    SSA->>AM: Commences Firebase
    SSA->>AVM: call getCurrentUser method
    AVM->>SSA: current user entity

    alt if current user is valid
        SSA->>HS: Navigate to Homescreen
    else

    SSA->>LS: Navigate to Login Screen

    alt clicks "Continue with Salesforce"
    LS->>AVM: call getConnectWithSalesForceUrl method
    AVM->>AR: call get method in ApiService with redirect_uri
    AR->>S: Request: Salesforce login URL
    note right of AR: Request: POST {api_base_url}/v1/auth/salesforce/redirect-url

    break If request fails
        S->>AR: Error
        AR->>AVM: Error message
        AVM->>LS: Displays Error message
    end

    S-->>AR: Success Response 
    AR->>AVM: Response with Login URL

    LS->>B: Open Browser with Login URL
    B->>SF: Login with Salesforce credentials
    SF-->>B: Auth code
    note right of B: (code:"")
    
    B->>LS: Redirect to App with Auth Code

    LS->>AVM: call salesForceConnect method with authcode
    AVM->>AR: invoke post method
    AR->>S: Request: Salesforce connect
    note right of AR: Request: POST {api_base_url}/v1/auth/salesforce/connect

    break If request fails
        S-->>AR: Error response
        AR->>AVM: Error message
        AVM->>LS: Displays Error message
    end

    S->>SSA: 
    Note over SSA: set user login cookie
    S-->>AR: Success response
    AR->>AVM: Response with user data
    note over AVM: Set current user data
    AVM->>HS: Navigate to Homescreen
    end
    end